---
swagger: "2.0"
info:
  description: "semaphore API and mutex API for Distributed locks"
  version: "1.0.0"
  title: "Distributed locks API"
host: "localhost:8080"
basePath: "/v1"
tags:
- name: "Semaphore"
- name: "Mutex"
schemes:
- "http"
paths:
  /semaphore/{semaphoreKey}:
    post:
      tags:
      - "Semaphore"
      summary: "Create a semaphore."
      description: "Creates a Semaphore with the given number of seats"
      operationId: "creatSemaphore"
      produces:
      - "application/json"
      parameters:
      - name: "semaphoreKey"
        in: "path"
        description: "semaphore identifier"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      - in: "body"
        name: "seat"
        description: "number of seats"
        required: false
        schema:
          $ref: "#/definitions/seat"
      responses:
        200:
          description: "semaphore status"
          schema:
            $ref: "#/definitions/Semaphore"
        409:
          description: "lock in use"
      x-swagger-router-controller: "Semaphore"
    get:
      tags:
      - "Semaphore"
      summary: "Query semaphore status"
      description: "Returns the current status in this semaphore."
      operationId: "querySemaphore"
      produces:
      - "application/json"
      parameters:
      - name: "semaphoreKey"
        in: "path"
        description: "semaphore identifier"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      responses:
        200:
          description: "semaphore status"
          schema:
            $ref: "#/definitions/Semaphore"
        404:
          description: "semaphore key not exist"
      x-swagger-router-controller: "Semaphore" 
    delete:
      tags:
      - "Semaphore" 
      summary: "Delete semaphore"
      description: "Delete semaphore when no one use"
      operationId: "deleteSemaphore"
      parameters:
      - name: "semaphoreKey"
        in: "path"
        description: "semaphore identifier"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      responses:
        200:
          description: "OK"
        409:
          description: "lock in use"
      x-swagger-router-controller: "Semaphore"
  /semaphore/{semaphoreKey}/seat:
    post:
      tags:
      - "Semaphore"
      summary: "Acquires a seat"
      description: "Acquires a seat from this semaphore" 
      operationId: "acquireSeat"
      parameters:
      - name: "semaphoreKey"
        in: "path"
        description: "semaphore identifier"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      - in: "body"
        name: "ttl"
        description: "update ttl"
        required: false
        schema:
          $ref: "#/definitions/ttl"
      responses:
        200:
          description: "semaphore status"
          schema:
            $ref: "#/definitions/SemaphoreHandler"
        409:
          description: "No Seat Available"
        404:
          description: Semaphore Key Not Exist
      x-swagger-router-controller: "Semaphore"
  /semaphore/{semaphoreKey}/seat/{semaphoreHandle}:
    delete:
      tags:
      - "Semaphore"
      summary: "Releases a seat"
      description: "releases a seat from this semaphore"
      operationId: "releasesSeat"
      parameters:
      - name: "semaphoreKey"
        in: "path"
        description: "semaphore identifier"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      - name: "semaphoreHandle"
        in: "path"
        description: "check seat owner"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Semaphore"
    patch:
      tags:
      - "Semaphore"
      summary: "update ttl"
      description: "update ttl"
      operationId: "extendttl"
      parameters:
      - name: "semaphoreKey"
        in: "path"
        description: "semaphore identifier"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      - name: "semaphoreHandle"
        in: "path"
        description: "check seat owner"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      - in: "body"
        name: "ttl"
        description: "update ttl"
        required: true
        schema:
          $ref: "#/definitions/ttl"
      responses:
        200:
          description: "semaphore status"
          schema:
            $ref: "#/definitions/Semaphore"
        404:
          description: "Handler Not Exist"
      x-swagger-router-controller: "Semaphore"
  /mutex/{mutexKey}:
    get:
      tags:
      - "Mutex"
      summary: "Query mutex status"
      operationId: "queryMutex"
      produces:
      - "application/json"
      parameters:
      - name: "mutexKey"
        in: "path"
        description: "Mutex identifier"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Mutex"
        400:
          description: "Invalid ID supplied"
      x-swagger-router-controller: "Mutex"
    post:
      tags:
      - "Mutex"
      summary: "Acquires the lock"
      operationId: "lockMutex"
      parameters:
      - name: "mutexKey"
        in: "path"
        description: "Mutex ID"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      - in: "body"
        name: "ttl"
        required: false
        schema:
          $ref: "#/definitions/ttl"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Mutex"
        409:
          description: "lock in use"
      x-swagger-router-controller: "Mutex"
  /mutex/{mutexKey}/{mutexHandle}:
    delete:
      tags:
      - "Mutex"
      summary: "Releases the lock"
      operationId: "unlockMutex"
      produces:
      - "application/json"
      parameters:
      - name: "mutexKey"
        in: "path"
        description: "Mutex ID"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      - name: "mutexHandle"
        in: "path"
        description: "Mutex id to delete"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Mutex"
        400:
          description: "Invalid ID Supplied"
      x-swagger-router-controller: "Mutex"
    patch:
      tags:
      - "Mutex"
      summary: "Update ttl"
      operationId: "extendMutex"
      parameters:
      - name: "mutexKey"
        in: "path"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      - name: "mutexHandle"
        in: "path"
        description: "Mutex id to delete"
        required: true
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      - in: "body"
        name: "mutex"
        required: true
        schema:
          $ref: "#/definitions/ttl"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Mutex"
        400:
          description: "Invalid ID Supplied"
      x-swagger-router-controller: "Mutex"
definitions:
  Semaphore:
    type: "object"
    required:
    - "seat"
    - "occupied"
    - "id"
    properties:
      id:
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      seat:
        type: "integer"
        format: "int64"
      occupied:
        type: "integer"
        format: "int64"
    example:
      id: "id"
      seat: 10
      occupied: 8
  SemaphoreHandler:
    type: "object"
    required:
    - "id"
    - "handler"
    - "expired"
    properties:
      id:
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$" 
      handler:
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      expired:
        type: "integer"
        format: "int64"
    example:
      id: "id"
      handler: "uuid"
      expiry: 1532486984
  Mutex:
    type: "object"
    required:
    - "expiry"
    - "id"
    properties:
      id:
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      handle:
        type: "string"
        pattern: "^[a-zA-Z0-9\\-_]+$"
      expiry:
        type: "integer"
        format: "int64"
    example:
      handle: "handle"
      id: "id"
      expiry: 1532486984
  ttl:
    type: "object"
    properties:
      ttl:
        type: "integer"
        minimum: 1
        maximum: 3600
  seat:
    type: "object"
    properties:
      seat:
        type: "integer"
        minimum: 1
        maximum: 10
